### ISSUE TITLE
[BE] Config files

### ISSUE THREAD

**Issue by kozabrada123** [SloveniaEngineering/laguna-backend#17]
My proposal:

.toml config files that can be overwriten by environment variables

ex:
Config.toml
`port = 8000`

No PORT enviornment variable

Server uses port 8000

----
Config.toml
`port = 8000`

Enviornment variables
`PORT=8080`

Server uses port 8080

**Comment by kenpaicat** [comment]
Boljša rešitev; default vrednosti bash okoljskih spremenljivk:

`PORT="${PORT:-default_value}"`

Pol se sploh .toml-om ni treba ukvarjat.

**Comment by kenpaicat** [comment]
Fixed in fee6bf974f91ed3e7685fddef87c6eb488ef8708
