### ISSUE TITLE
Weird Access and Refresh Token liftetimes

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-backend#46]
Reported by @zigapovhe

**Comment by zigapovhe** [comment]
- Access token expires in 1min after successful login
- Refresh token expires after 30min

Testing: Try to decode JWT token with any public available tools and check for exp field.

**Comment by kenpaicat** [comment]
Should be fixed by a6e0b1

**Comment by kenpaicat** [comment]
Yep
