### ISSUE TITLE
[BE] Getting HTTP 500 on register endpoint

### ISSUE THREAD

**Issue by zigapovhe** [SloveniaEngineering/laguna-backend#76]
I'm getting "HTTP 500 - Internal Server error" every time I try to register with username that already exists, and mail that doesn't or vice versa. Backend should probably return HTTP 208.

**Comment by kenpaicat** [comment]
Problem is in https://github.com/SloveniaEngineering/laguna-backend/blob/c1cd07846200f55b49b7ca3b1c1d48a253851fda/crates/laguna-backend-api/src/register.rs#L41

The "AND" should really be "OR", because only if either username or email exist, then the its "already registered".
